// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package repository

import (
	"database/sql"
)

type Monitor struct {
	ID        int64        `json:"id"`
	UserID    int64        `json:"user_id"`
	Url       string       `json:"url"`
	CreatedAt sql.NullTime `json:"created_at"`
	UpdatedAt sql.NullTime `json:"updated_at"`
}

type User struct {
	ID         int64        `json:"id"`
	ProviderID string       `json:"provider_id"`
	Provider   string       `json:"provider"`
	Name       string       `json:"name"`
	Email      string       `json:"email"`
	Status     int64        `json:"status"`
	CreatedAt  sql.NullTime `json:"created_at"`
	UpdatedAt  sql.NullTime `json:"updated_at"`
}
