// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package repository

import (
	"database/sql"
)

type HttpMonitor struct {
	MonitorID           int64          `json:"monitor_id"`
	Url                 string         `json:"url"`
	IntervalS           int64          `json:"interval_s"`
	Retries             int64          `json:"retries"`
	TimeoutS            int64          `json:"timeout_s"`
	ExpectedStatusCodes string         `json:"expected_status_codes"`
	HttpMethod          string         `json:"http_method"`
	HttpBody            sql.NullString `json:"http_body"`
	HttpHeaders         sql.NullString `json:"http_headers"`
}

type Monitor struct {
	ID        int64        `json:"id"`
	UserID    int64        `json:"user_id"`
	Name      string       `json:"name"`
	Type      string       `json:"type"`
	CreatedAt sql.NullTime `json:"created_at"`
	UpdatedAt sql.NullTime `json:"updated_at"`
}

type User struct {
	ID         int64        `json:"id"`
	ProviderID string       `json:"provider_id"`
	Provider   string       `json:"provider"`
	Name       string       `json:"name"`
	Email      string       `json:"email"`
	Status     int64        `json:"status"`
	CreatedAt  sql.NullTime `json:"created_at"`
	UpdatedAt  sql.NullTime `json:"updated_at"`
}
